apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: us-central1-docker.pkg.dev/ambient-tuner-373312/my-repo/app:latest
        ports:
        - containerPort: 8080

apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: app
description: Hello World Deployment Pipeline 
serialPipeline:
  stages:
  - targetId: staging
  - targetId: production
