---
apiVersion: deploy.cloud.google.com/v1beta1
kind: DeliveryPipeline
metadata:
  name: app-deployment
description: Hello World Deployment Pipeline 
serialPipeline:
  stages:
    - targetId: staging
    - targetId: production

