# Step 1: Build the Docker image
steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/ambient-tuner-373312/my-repo/app:$SHORT_SHA', '.']
  id: 'Build Docker Image'
  waitFor: ['-']  # This ensures the step starts immediately. 

# Step 2: Push the Docker image to Google Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/ambient-tuner-373312/my-repo/app:$SHORT_SHA']
  id: 'Push to Artifact Registry'
  waitFor: ['Build Docker Image']  # This ensures the push only happens after the build step completes.


